server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/catalogdb
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
