server:
  port: 8082
spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/inventorydb
      username: postgres
      password: 12345
      driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: create-drop
