server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

url:
  inventory: http://yumasday:8082/api/v1/inventory
  catalog: http://yumasday:8081/api/v1/catalog/offers
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp